default:
  outputs:
    dev:
      dataset: dbt_frederikms
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: /mnt/c/Users/frede/OneDrive/Dokumenter/Pyne_case/pynes-case-50f5db6cfad9.json
      location: US
      method: service-account
      priority: interactive
      project: pynes-case
      threads: 1
      type: bigquery
  target: dev
