name: Install DBT with Nix

on:
  pull_request:


jobs:
  install-dbt:
    runs-on: ubuntu-latest
  steps:
  - name: dbt Simple Action
    uses: CedricLeong/dbt-action-nix@v1
  - name: Checkout repositoryS
    uses: actions/checkout@v4
  - name: Install DBT using Nix
    uses: CedricLeong/install-dbt-action-nix@v1
  - name: Verify DBT installation
    run: dbt --version
  - name: Run DBT command
    run: |
      dbt run
      dbt test
