name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install poetry
      uses: abatilo/actions-poetry@v4
    - name: Setup a local virtual environment (if no poetry.toml file)
      run: |
        poetry config virtualenvs.create true --local
        poetry config virtualenvs.in-project true --local
    - uses: actions/cache@v3
      name: Define a cache for the virtual environment based on the dependencies lock file
      with:
        path: ./.venv
        key: venv-${{ hashFiles('poetry.lock') }}
    - name: Install the project dependencies
      run: poetry install
    - name: Set up dbt profiles directory
      run: |
        mkdir -p ~/.dbt
        echo "${DBT_PROFILES_YML}" > ~/.dbt/profiles.yml
      env:
        DBT_PROFILES_YML: ${{ secrets.DBT_PROFILES_YML }}
    - name: Debug profile file
      run: |
        echo "Contents of ~/.dbt:"
        ls -la ~/.dbt
        echo "profiles.yml content:"
        cat ~/.dbt/profiles.yml
    - name: dbt
      run: |
        poetry run dbt run
        poetry run dbt test
